version: '3'

services:
  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: book_search_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      ports: "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql

volumes:
  bundle:
  mysql_data:
